### ISSUE TITLE
cross-domain-detection

### ISSUE THREAD

**Issue by OUYANGDING** [nicaogr/Mi_max#3]
Hi, I want to know how to get the cross-domain-detection dataset, because I can't run the Mimax without the dataset.

**Comment by ngonthier** [comment]
Hi,
The cross domain detection datasets are provided by Naoto Inoue and can be found here : https://github.com/naoto0804/cross-domain-detection
You have to use the prepare.sh script to download the datasets : https://github.com/naoto0804/cross-domain-detection/blob/master/datasets/prepare.sh

**Comment by OUYANGDING** [comment]
> Hi,
> The cross domain detection datasets are provided by Naoto Inoue and can be found here : https://github.com/naoto0804/cross-domain-detection
> You have to use the prepare.sh script to download the datasets : https://github.com/naoto0804/cross-domain-detection/blob/master/datasets/prepare.sh

Thanks a lot! Sorry to disturb you again, I have another problem, that I want to know where to download wikidata-painting and VOCdevkit. Then if you can, can you show me the file directory, because there are some problems in the file path. Thanks again!

**Comment by ngonthier** [comment]
The IconArt dataset can be found here as mentioned in the README : https://wsoda.telecom-paristech.fr/downloads/dataset/ 
Whereas the VOCdevkit (2007) is available here : http://host.robots.ox.ac.uk/pascal/VOC/voc2007/

The dataset folder have to be put in the data/ folder normally. 

Don't hesitate to say me if you still have an issue with the path.
